version: '3'
services:
  server:
    build: ./
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      REDIS_URL: 'redis://:uhZFz0IRHVCGxkCIPPlHY5aazKWsl8ef@redis-16023.c238.us-central1-2.gce.cloud.redislabs.com:16023'
    env_file:
      - .env
